[tool.poetry]
name = "geneticalgorithm"
version = "0.1.0"
description = ""
authors = ["Gideon Oludeyi <go21zq@brocku.ca>"]
readme = "README.md"

[tool.poetry.scripts]
geneticalgorithm = "geneticalgorithm.__main__:main"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
